### ISSUE TITLE
Swift 5.3 unavailable

### ISSUE THREAD

**Issue by mxcl** [fwal/setup-swift#131]
```
Run fwal/setup-swift@v1
Error: Unexpected error, unable to continue. Please report at https://github.com/fwal/setup-swift/issues
Version "5.3" is not available
Stacktrace:
Error: Version "5.3" is not available
    at Object.verify (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:7770:15)
    at /home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:2498:36
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:2483:71
    at new Promise (<anonymous>)
    at module.exports.198.__awaiter (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:2479:12)
    at run (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:2495:12)
    at Object.198 (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:2525:1)
    at __webpack_require__ (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:43:19)
```

**Workflow Configuration:**

```yaml
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
        - 5.1
        - 5.2
        - 5.3
    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}

**Comment by fwal** [comment]
Oh wow, I managed to not push the update to the v1 tag 🤦
Fixed now, thanks! 👍
