### ISSUE TITLE
Can't install: not found error

### ISSUE THREAD

**Issue by mingrammer** [fwal/setup-swift#196]
**Describe the bug**

I've got the following error while setting up the swift.

```
Run fwal/setup-swift@v1
  with:
    swift-version: 5.2.0
  env:
    GOROOT: /opt/hostedtoolcache/go/1.14.15/x64
/usr/bin/gpg --import /home/runner/work/_temp/9defb481-683b-47ab-af80-d97c089c074c
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
gpg: key D441C977412B37AD: public key "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" imported
gpg: key 9F597F4D21A56D5F: public key "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: key 63BC1CFE91D306C6: public key "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: key EF5430F071E1B235: public key "Swift 4.x Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: key 7638F1FB2B2B08C4: public key "Swift Automatic Signing Key #2 <swift-infrastructure@swift.org>" imported
gpg: key 925CC1CCED3D1561: public key "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: key FAF6989E1BC16FEA: public key "Swift Automatic Signing Key #3 <swift-infrastructure@swift.org>" imported
gpg: Total number processed: 7
gpg:               imported: 7
/usr/bin/gpg --keyserver hkp://pool.sks-keyservers.net --refresh-keys Swift
gpg: refreshing 7 keys from hkp://pool.sks-keyservers.net
gpg: key FAF6989E1BC16FEA: "Swift Automatic Signing Key #3 <swift-infrastructure@swift.org>" not changed
gpg: key 925CC1CCED3D1561: "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" not changed
gpg: key 7638F1FB2B2B08C4: "Swift Automatic Signing Key #2 <swift-infrastructure@swift.org>" not changed
gpg: key EF5430F071E1B235: "Swift 4.x Release Signing Key <swift-infrastructure@swift.org>" not changed
gpg: key 63BC1CFE91D306C6: "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" not changed
gpg: key 9F597F4D21A56D5F: "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" not changed
gpg: key D441C977412B37AD: "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" not changed
gpg: Total number processed: 7
gpg:              unchanged: 7
Error: Unexpected error, unable to continue. Please report at https://github.com/fwal/setup-swift/issues
Unexpected HTTP response: 404
Stacktrace:
Error: Unexpected HTTP response: 404
    at /home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:8815:25
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:8720:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Workflow configuration (please complete the following information):**

- Platform: ubuntu-latest
- Swift version: 5.2.0

**Comment by fwal** [comment]
Hi @mingrammer and thanks for reporting this!

The version of Swift you are trying to use, Swift 5.2.0, is unfortunately not available on Ubuntu 20.04 (that `ubuntu-latest` resolves to).

Either change the version of Ubuntu used to 18.04 (`ubuntu-18.04`) or the version of Swift to 5.2.4 or above.

(Tip: if you set the swift-version to 5.2 it will automatically select the latest 5.2.x version)

I'll see if I can make this particular error a bit clearer in the future.

**Comment by mingrammer** [comment]
I'll try that. Thank you.

**Comment by fwal** [comment]
Some additional info for future reference [GitHub changelog update](https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04/)
