### ISSUE TITLE
Error: Version "20.04" of Ubuntu is not supported

### ISSUE THREAD

**Issue by bander-saeed94** [fwal/setup-swift#73]
##[error]Unexpected error, unable to continue. Please report at https://github.com/fwal/setup-swift/issues
Version "20.04" of Ubuntu is not supported
Stacktrace:
Error: Version "20.04" of Ubuntu is not supported
    at Object.<anonymous> (/home/runner/work/_actions/fwal/setup-swift/v1.0.1/dist/index.js:7541:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/fwal/setup-swift/v1.0.1/dist/index.js:7494:58)

**Comment by fwal** [comment]
Thanks for reporting this @bander-saeed94! What platform is the workflow configured to run on and what version of swift is requested?

**Comment by fwal** [comment]
Related to #61
