### ISSUE TITLE
Cannot install Swift

### ISSUE THREAD

**Issue by Samasaur1** [fwal/setup-swift#77]
**Describe the bug**
setup-swift cannot install swift

**Workflow configuration (please complete the following information):**
 - Platform (`runs-on`): [ubuntu-latest, ubuntu-16.04] (seen on both of them)
 - Swift version (`swift-version`): [5.1, 5.2] (seen on both of them)

**Stack trace:** (this specific example is ubuntu-16.04, swift 5.1
```
##[group]Run fwal/setup-swift@v1
2020-07-01T16:59:22.2108114Z with:
2020-07-01T16:59:22.2108253Z   swift-version: 5.1
2020-07-01T16:59:22.2108394Z ##[endgroup]
2020-07-01T16:59:22.6849068Z [command]/usr/bin/gpg --import /home/runner/work/_temp/54452a17-888b-4684-a271-0bac2b915336
2020-07-01T16:59:22.6952448Z gpg: directory `/home/runner/.gnupg' created
2020-07-01T16:59:22.6957929Z gpg: new configuration file `/home/runner/.gnupg/gpg.conf' created
2020-07-01T16:59:22.6958602Z gpg: WARNING: options in `/home/runner/.gnupg/gpg.conf' are not yet active during this run
2020-07-01T16:59:22.6964182Z gpg: keyring `/home/runner/.gnupg/secring.gpg' created
2020-07-01T16:59:22.6964786Z gpg: keyring `/home/runner/.gnupg/pubring.gpg' created
2020-07-01T16:59:22.7008328Z gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
2020-07-01T16:59:22.7009032Z gpg: key 412B37AD: public key "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" imported
2020-07-01T16:59:22.7020489Z gpg: key 21A56D5F: public key "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" imported
2020-07-01T16:59:22.7030816Z gpg: key 91D306C6: public key "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" imported
2020-07-01T16:59:22.7041370Z gpg: key 71E1B235: public key "Swift 4.x Release Signing Key <swift-infrastructure@swift.org>" imported
2020-07-01T16:59:22.7062368Z gpg: key 2B2B08C4: public key "Swift Automatic Signing Key #2 <swift-infrastructure@swift.org>" imported
2020-07-01T16:59:22.7072914Z gpg: key ED3D1561: public key "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" imported
2020-07-01T16:59:22.7084067Z gpg: key 1BC16FEA: public key "Swift Automatic Signing Key #3 <swift-infrastructure@swift.org>" imported
2020-07-01T16:59:22.7084283Z gpg: Total number processed: 7
2020-07-01T16:59:22.7084436Z gpg:               imported: 7  (RSA: 7)
2020-07-01T16:59:22.7116840Z [command]/usr/bin/gpg --keyserver hkp://pool.sks-keyservers.net --refresh-keys Swift
2020-07-01T16:59:22.7158926Z gpg: refreshing 7 keys from hkp://pool.sks-keyservers.net
2020-07-01T16:59:22.7166407Z gpg: requesting key 412B37AD from hkp server pool.sks-keyservers.net
2020-07-01T16:59:22.7167507Z gpg: requesting key 21A56D5F from hkp server pool.sks-keyservers.net
2020-07-01T16:59:22.7168595Z gpg: requesting key 91D306C6 from hkp server pool.sks-keyservers.net
2020-07-01T16:59:22.7169176Z gpg: requesting key 71E1B235 from hkp server pool.sks-keyservers.net
2020-07-01T16:59:22.7169699Z gpg: requesting key 2B2B08C4 from hkp server pool.sks-keyservers.net
2020-07-01T16:59:22.7170303Z gpg: requesting key ED3D1561 from hkp server pool.sks-keyservers.net
2020-07-01T16:59:22.7170840Z gpg: requesting key 1BC16FEA from hkp server pool.sks-keyservers.net
2020-07-01T16:59:23.4466621Z gpgkeys: key 7463A81A4B2EEA1B551FFBCFD441C977412B37AD can't be retrieved
2020-07-01T16:59:24.0763053Z gpgkeys: key 1BE1E29A084CB305F397D62A9F597F4D21A56D5F can't be retrieved
2020-07-01T16:59:24.7034462Z gpgkeys: key A3BAFD3556A59079C06894BD63BC1CFE91D306C6 can't be retrieved
2020-07-01T16:59:25.0545510Z gpgkeys: key 5E4DF843FB065D7F7E24FBA2EF5430F071E1B235 can't be retrieved
2020-07-01T16:59:25.4889131Z gpgkeys: key 8513444E2DA36B7C1659AF4D7638F1FB2B2B08C4 can't be retrieved
2020-07-01T16:59:25.8369934Z gpgkeys: key A62AE125BBBFBB96A6E042EC925CC1CCED3D1561 can't be retrieved
2020-07-01T16:59:26.8374338Z gpgkeys: key 8A7495662C3CD4AE18D95637FAF6989E1BC16FEA can't be retrieved
2020-07-01T16:59:26.8390578Z gpg: no valid OpenPGP data found.
2020-07-01T16:59:26.8390914Z gpg: Total number processed: 0
2020-07-01T16:59:26.8391131Z gpg: keyserver communications error: keyserver helper general error
2020-07-01T16:59:26.8391357Z gpg: keyserver communications error: unknown pubkey algorithm
2020-07-01T16:59:26.8394943Z gpg: keyserver refresh failed: unknown pubkey algorithm
2020-07-01T16:59:26.8423108Z ##[error]Unexpected error, unable to continue. Please report at https://github.com/fwal/setup-swift/issues
The process '/usr/bin/gpg' failed with exit code 2
Stacktrace:
Error: The process '/usr/bin/gpg' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:926:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:909:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:803:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by Samasaur1** [comment]
I don't know if GitHub Actions are publicly visible, but there's a series of failed actions here: https://github.com/Samasaur1/DiceKit/actions

**Comment by fwal** [comment]
Hi @Samasaur1, thanks for reporting! Seems like the key server is a bit unstable from time to time, I'll look into it!

**Comment by Samasaur1** [comment]
Thanks! I tried it again today, and it's been working, so ¯\_(ツ)_/¯. It'd be great if it was 100% stable, but then again, so would a billion dollars…

**Comment by Samasaur1** [comment]
Right as I said it, it happened again:
```

2020-07-02T17:46:24.8029046Z ##[group]Run fwal/setup-swift@v1
2020-07-02T17:46:24.8029221Z with:
2020-07-02T17:46:24.8029348Z   swift-version: 5.1
2020-07-02T17:46:24.8029490Z ##[endgroup]
2020-07-02T17:46:25.2827366Z [command]/usr/bin/gpg --import /home/runner/work/_temp/ea59f2fe-085e-4a1b-9d31-e939d1a7b6b5
2020-07-02T17:46:25.2919376Z gpg: directory `/home/runner/.gnupg' created
2020-07-02T17:46:25.2921294Z gpg: new configuration file `/home/runner/.gnupg/gpg.conf' created
2020-07-02T17:46:25.2922163Z gpg: WARNING: options in `/home/runner/.gnupg/gpg.conf' are not yet active during this run
2020-07-02T17:46:25.2922963Z gpg: keyring `/home/runner/.gnupg/secring.gpg' created
2020-07-02T17:46:25.2923970Z gpg: keyring `/home/runner/.gnupg/pubring.gpg' created
2020-07-02T17:46:25.2962834Z gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
2020-07-02T17:46:25.2964515Z gpg: key 412B37AD: public key "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" imported
2020-07-02T17:46:25.2966000Z gpg: key 21A56D5F: public key "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" imported
2020-07-02T17:46:25.2969769Z gpg: key 91D306C6: public key "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" imported
2020-07-02T17:46:25.2981002Z gpg: key 71E1B235: public key "Swift 4.x Release Signing Key <swift-infrastructure@swift.org>" imported
2020-07-02T17:46:25.2991551Z gpg: key 2B2B08C4: public key "Swift Automatic Signing Key #2 <swift-infrastructure@swift.org>" imported
2020-07-02T17:46:25.3002137Z gpg: key ED3D1561: public key "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" imported
2020-07-02T17:46:25.3013972Z gpg: key 1BC16FEA: public key "Swift Automatic Signing Key #3 <swift-infrastructure@swift.org>" imported
2020-07-02T17:46:25.3014756Z gpg: Total number processed: 7
2020-07-02T17:46:25.3016959Z gpg:               imported: 7  (RSA: 7)
2020-07-02T17:46:25.3043132Z [command]/usr/bin/gpg --keyserver hkp://pool.sks-keyservers.net --refresh-keys Swift
2020-07-02T17:46:25.3083650Z gpg: refreshing 7 keys from hkp://pool.sks-keyservers.net
2020-07-02T17:46:25.3092798Z gpg: requesting key 412B37AD from hkp server pool.sks-keyservers.net
2020-07-02T17:46:25.3094072Z gpg: requesting key 21A56D5F from hkp server pool.sks-keyservers.net
2020-07-02T17:46:25.3095005Z gpg: requesting key 91D306C6 from hkp server pool.sks-keyservers.net
2020-07-02T17:46:25.3096001Z gpg: requesting key 71E1B235 from hkp server pool.sks-keyservers.net
2020-07-02T17:46:25.3096930Z gpg: requesting key 2B2B08C4 from hkp server pool.sks-keyservers.net
2020-07-02T17:46:25.3097906Z gpg: requesting key ED3D1561 from hkp server pool.sks-keyservers.net
2020-07-02T17:46:25.3098906Z gpg: requesting key 1BC16FEA from hkp server pool.sks-keyservers.net
2020-07-02T17:46:57.5355143Z gpgkeys: key 7463A81A4B2EEA1B551FFBCFD441C977412B37AD can't be retrieved
2020-07-02T17:47:30.1354151Z gpgkeys: key 1BE1E29A084CB305F397D62A9F597F4D21A56D5F can't be retrieved
2020-07-02T17:47:31.5727511Z gpg: key 91D306C6: "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" not changed
2020-07-02T17:47:31.9239401Z gpg: key 71E1B235: "Swift 4.x Release Signing Key <swift-infrastructure@swift.org>" not changed
2020-07-02T17:47:32.4862721Z gpg: key 2B2B08C4: "Swift Automatic Signing Key #2 <swift-infrastructure@swift.org>" 1 new signature
2020-07-02T17:47:32.4889829Z gpg: key ED3D1561: "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" not changed
2020-07-02T17:47:32.4944923Z gpg: key 1BC16FEA: "Swift Automatic Signing Key #3 <swift-infrastructure@swift.org>" not changed
2020-07-02T17:47:32.4945459Z gpg: Total number processed: 5
2020-07-02T17:47:32.4945779Z gpg:              unchanged: 4
2020-07-02T17:47:32.4946118Z gpg:         new signatures: 1
2020-07-02T17:47:32.4946435Z gpg: keyserver communications error: keyserver helper general error
2020-07-02T17:47:32.4946959Z gpg: keyserver communications error: unknown pubkey algorithm
2020-07-02T17:47:32.4947299Z gpg: no ultimately trusted keys found
2020-07-02T17:47:32.4947903Z gpg: keyserver refresh failed: unknown pubkey algorithm
2020-07-02T17:47:32.4951456Z ##[error]Unexpected error, unable to continue. Please report at https://github.com/fwal/setup-swift/issues
The process '/usr/bin/gpg' failed with exit code 2
Stacktrace:
Error: The process '/usr/bin/gpg' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:926:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:909:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:803:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```
This was Swift 5.1 on ubuntu-16.04 again, so maybe it's specifically that?

**Comment by fwal** [comment]
I've pushed out a new version that uses a pool of key servers instead of a single one.
Let me know if that sort things out for you @Samasaur1.

**Comment by Samasaur1** [comment]
I'll be sure to let you know, but it seems to be working so far

**Comment by Samasaur1** [comment]
This does seem to be working nicely

**Comment by fwal** [comment]
That’s great! I’m closing this, feel free to reopen if the problem returns.
